clc; clear;
grain = imread("..\image\grain.tif");
L = 256;
h = zeros(1, L);
num = 1:L;
[r, c] = size(grain);

%% histogram
for i = 1:r
    for j = 1:c
        tmp = grain(i, j);
        h(tmp) = h(tmp) + 1;
    end
end

%% compute s_k
p = h / (r * c);
s = zeros(1, L);
s(1) = p(1);
for cnt = 2:L
    s(cnt) = s(cnt-1) + p(cnt);
end

%% histogram equalization
figure(1)
% hist equa generated by myself
outimg = uint8(zeros(r,c));
for cnt = 1:L
    s(cnt) = floor((s(cnt)-min(s))/(1-min(s)) * (L-1) + 0.5);
end
for i = 1:r
    for j = 1:c
        outimg(i,j) = s(grain(i,j));
    end
end

hout = zeros(1, L);
numout = 1:L;
for i = 1:r
    for j = 1:c
        tmp = outimg(i, j);
        hout(tmp) = hout(tmp) + 1;
    end
end

subplot(2,1,1)
bar(numout, hout, 1.5);
title("hist equa generated by myself")

% hist equa generated by matlab function
hs1 = histeq(grain);
subplot(2,1,2)
histogram(hs1)
title("hist equa generated by matlab function")
axis('auto')

figure(2)
subplot(1,3,1)
imshow(grain)
title("original image")
subplot(1,3,2)
imshow(outimg)
title("my histeq image")
subplot(1,3,3)
imshow(hs1)
title("histeq image by matlab")

